services:
  api-server:
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

  redis-server:
    ports:
      - "${REDIS_PORT}:6379"

  postgres-server:
    ports:
      - "${POSTGRES_PORT}:5432"

  elasticmq-server:
    ports:
      - "${ELASTICMQ_PORT}:9324"
      - "${ELASTICMQ_UI_PORT}:9325"
