include classpath("application.conf")

queues {
  orders-queue {
    deadLettersQueue {
        name = "orders-queue-dlq"
        maxReceiveCount = 3
    }
    receiveMessageWait = 0 seconds
    defaultVisibilityTimeout = 10 seconds
  }
  orders-queue-dlq {}
}
