app:
  jwt:
    secret: 9YpXKW0JZF+mHw2VV4iSlvInM+7Hd5mgjTf9Ihu4xlQ=
  security:
    username: admin
    password: admin
  rate-limit:
    capacity: 100

server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: redis
  datasource:
    url: jdbc:postgresql://localhost:5432/db_delivery_orders
    username: postgres
    password: postgres

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
